name: Upload DAGs to S3

on:
  push:
    branches: [ main ]
    paths:
      - 'dags/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Upload DAGs to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 sync dags/ s3://${{ secrets.MWAA_DAG_BUCKET }}/dags/ --delete