name: Deploy Infrastructure with Terraform
on:
  push:
    branches: [ master ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Debug subnet_ids secret
      run: |
        echo ${{ secrets.SUBNET_IDS }}
        echo ${{ secrets.TEST_SUBNETS }}

    - name: Terraform Plan
      env:
        TF_VAR_security_group_id: ${{ secrets.SECURITY_GROUP_ID }}
        TF_VAR_twitter_bearer_token: ${{ secrets.TWITTER_BEARER_TOKEN }}
      run: |
        terraform plan -input=false -lock=false -var='subnet_ids=["subnet-07b2df2f5c793f6a4", "subnet-061b1c272720ac475"]' -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan